import { formatHour, startOfDay } from '../lib/time'
import { minutesToLength } from '../lib/scale'

/**
 * The hour labels down the left edge.
 *
 * Labels are generated by adding real hours to local midnight rather than by
 * counting 0..23, so a spring-forward day simply has no 02:00 row and a
 * fall-back day repeats 01:00 — which is what the clock actually did.
 */
export function HourGutter({
  dateKey,
  timeZone,
  hours,
}: {
  dateKey: string
  timeZone: string
  hours: number
}) {
  const midnight = startOfDay(dateKey, timeZone)

  return (
    <div className="relative w-12 shrink-0" aria-label="Hours">
      {Array.from({ length: hours }, (_, index) => {
        const instant = new Date(midnight.getTime() + index * 3_600_000)
        return (
          <div
            key={index}
            className="absolute right-1 -translate-y-1/2 text-[0.6875rem] text-muted tabular-nums"
            style={{ top: minutesToLength(index * 60) }}
          >
            {index === 0 ? '' : formatHour(instant, timeZone)}
          </div>
        )
      })}
    </div>
  )
}

export function HourLines({ hours }: { hours: number }) {
  return (
    <div className="pointer-events-none absolute inset-0">
      {Array.from({ length: hours }, (_, index) => (
        <div
          key={index}
          className="absolute inset-x-0 border-t border-paper/8"
          style={{ top: minutesToLength(index * 60) }}
        />
      ))}
    </div>
  )
}
